package com.smartcampus.model;

public enum NotifType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_CREATED,
    TICKET_UPDATED,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    COMMENT_ADDED,
    SECURITY_UPDATE,
    RESOURCE_UPDATE
}