spring.application.name=smart-campus-api
# MongoDB: Spring Boot 4 uses spring.mongodb.* (see application-local.properties for URI)

spring.mongodb.database=smart_campus
server.port=8081
logging.level.org.springframework.data.mongodb=DEBUG
spring.profiles.active=local